name: Daily Telemetry Fetch

on:
  schedule:
    - cron: '0 12 * * *'  # daily run at 12:00 UTC
  workflow_dispatch:

permissions:
  contents: write

jobs:
  fetch-and-commit:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Run telemetry fetch script
      run: |
        python fetch_telemetry.py

    - name: Commit and push changes
      env:
        TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "actions@github.com"
        git add .
        git commit -m "Automated telemetry update" || echo "No changes to commit"
        git push https://x-access-token:${TOKEN}@github.com/${{ github.repository }}.git
